


all:main.o VectorZL.o
	g++ main.o VectorZL.o -o tst
main.o: main.cpp
	g++ -c main.cpp
VectorZL.o: VectorZL.h VectorZL.cpp
	g++ -c VectorZL.cpp
clr:
	rm *.o
	rm tst
test:
	@./tst
	
	
	
	
	
	
	
	
	
	
	
	
	
