
​UPDATE Dmodele
SET DLIBELLEMODELE='Seat Alhambra'
WHERE DCODEMODELE=1 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Altea'
WHERE DCODEMODELE=2 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Altea XL'
WHERE DCODEMODELE=3 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Arosa'
WHERE DCODEMODELE=4 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Cordoba'
WHERE DCODEMODELE=5 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Cordoba Vario'
WHERE DCODEMODELE=6 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Exeo'
WHERE DCODEMODELE=7 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Ibiza'
WHERE DCODEMODELE=8 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Ibiza ST'
WHERE DCODEMODELE=9 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Exeo ST'
WHERE DCODEMODELE=10 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Leon'
WHERE DCODEMODELE=11 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Leon ST'
WHERE DCODEMODELE=12 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Inca'
WHERE DCODEMODELE=13 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Seat Mii'
WHERE DCODEMODELE=14 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Renault Captur'
WHERE DCODEMODELE=15 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Clio'
WHERE DCODEMODELE=16 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='Clio Grandtour'
WHERE DCODEMODELE=17 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioEspace'
WHERE DCODEMODELE=18 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioExpress'
WHERE DCODEMODELE=19 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioFluence'
WHERE DCODEMODELE=20 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioGrand Espace'
WHERE DCODEMODELE=21 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioGrand Modus'
WHERE DCODEMODELE=22 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioGrand Scenic'
WHERE DCODEMODELE=23 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioKadjar'
WHERE DCODEMODELE=24 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioKangoo'
WHERE DCODEMODELE=25 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioKangoo Express'
WHERE DCODEMODELE=26 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioKoleos'
WHERE DCODEMODELE=27 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioLaguna'
WHERE DCODEMODELE=28 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioLaguna Grandtour'
WHERE DCODEMODELE=29 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioLatitude'
WHERE DCODEMODELE=30 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioMascott'
WHERE DCODEMODELE=31 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioMégane'
WHERE DCODEMODELE=32 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioMégane CC'
WHERE DCODEMODELE=33 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioMégane Combi'
WHERE DCODEMODELE=34 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioMégane Grandtour'
WHERE DCODEMODELE=35 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioMégane Coupé'
WHERE DCODEMODELE=36 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioMégane Scénic'
WHERE DCODEMODELE=37 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioScénic'
WHERE DCODEMODELE=38 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioTalisman'
WHERE DCODEMODELE=39 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioTalisman Grandtour'
WHERE DCODEMODELE=40 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='ClioThalia'
WHERE DCODEMODELE=41 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioTwingo'
WHERE DCODEMODELE=42 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='ClioWind'
WHERE DCODEMODELE=43 ;
   
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 1007'
WHERE DCODEMODELE=44 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 107'
WHERE DCODEMODELE=45 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 106'
WHERE DCODEMODELE=46 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 108'
WHERE DCODEMODELE=47 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 2008'
WHERE DCODEMODELE=48 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 205'
WHERE DCODEMODELE=49 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 205 Cabrio'
WHERE DCODEMODELE=50 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 206'
WHERE DCODEMODELE=51 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 206 CC'
WHERE DCODEMODELE=52 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 206 SW'
WHERE DCODEMODELE=53 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 207'
WHERE DCODEMODELE=54 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 207 CC'
WHERE DCODEMODELE=55 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 207 SW'
WHERE DCODEMODELE=56 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 306'
WHERE DCODEMODELE=57 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 307'
WHERE DCODEMODELE=58 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 307 CC'
WHERE DCODEMODELE=59 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 307 SW'
WHERE DCODEMODELE=60 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 308'
WHERE DCODEMODELE=61 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 308 CC'
WHERE DCODEMODELE=62 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 308 SW'
WHERE DCODEMODELE=63 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 309'
WHERE DCODEMODELE=64 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 4007'
WHERE DCODEMODELE=65 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 4008'
WHERE DCODEMODELE=66 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 405'
WHERE DCODEMODELE=67 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 406'
WHERE DCODEMODELE=68 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 407'
WHERE DCODEMODELE=69 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 407 SW'
WHERE DCODEMODELE=70 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 5008'
WHERE DCODEMODELE=71 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 508'
WHERE DCODEMODELE=72 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 508 SW'
WHERE DCODEMODELE=73 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 605'
WHERE DCODEMODELE=74 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 806'
WHERE DCODEMODELE=75 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 607'
WHERE DCODEMODELE=76 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot 807'
WHERE DCODEMODELE=77 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Peugeot Bipper'
WHERE DCODEMODELE=78 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Dacia Dokker'
WHERE DCODEMODELE=79 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Dacia Duster'
WHERE DCODEMODELE=80 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Dacia Lodgy'
WHERE DCODEMODELE=81 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Dacia Logan'
WHERE DCODEMODELE=82 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Dacia Logan MCV'
WHERE DCODEMODELE=83 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Dacia Logan Van'
WHERE DCODEMODELE=84 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Dacia Sandero'
WHERE DCODEMODELE=85 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën Berlingo'
WHERE DCODEMODELE=86 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C-Crosser'
WHERE DCODEMODELE=87 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C-Elissée'
WHERE DCODEMODELE=88 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C-Zero'
WHERE DCODEMODELE=89 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C1'
WHERE DCODEMODELE=90 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C2'
WHERE DCODEMODELE=91 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C3'
WHERE DCODEMODELE=92 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C3 Picasso'
WHERE DCODEMODELE=93 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C4'
WHERE DCODEMODELE=94 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C4 Aircross'
WHERE DCODEMODELE=95 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C4 Cactus'
WHERE DCODEMODELE=96 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C4 Coupé'
WHERE DCODEMODELE=97 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C4 Grand Picasso'
WHERE DCODEMODELE=98 ;
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C4 Sedan'
WHERE DCODEMODELE=99 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C5'
WHERE DCODEMODELE=100 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C5 Break'
WHERE DCODEMODELE=101 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C5 Tourer'
WHERE DCODEMODELE=102 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C6'
WHERE DCODEMODELE=103 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën C8'
WHERE DCODEMODELE=104 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën DS3'
WHERE DCODEMODELE=105 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën DS4'
WHERE DCODEMODELE=106 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën DS5'
WHERE DCODEMODELE=107 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën Evasion'
WHERE DCODEMODELE=108 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën Jumper'
WHERE DCODEMODELE=109 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën Jumpy'
WHERE DCODEMODELE=110 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën Saxo'
WHERE DCODEMODELE=111 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën Nemo'
WHERE DCODEMODELE=112 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Citroën Xantia'
WHERE DCODEMODELE=113 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Agila'
WHERE DCODEMODELE=114 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Ampera'
WHERE DCODEMODELE=115 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Antara'
WHERE DCODEMODELE=116 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Astra'
WHERE DCODEMODELE=117 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Astra cabrio'
WHERE DCODEMODELE=118 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Astra caravan'
WHERE DCODEMODELE=119 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Astra coupé'
WHERE DCODEMODELE=120 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Calibra'
WHERE DCODEMODELE=121 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Campo'
WHERE DCODEMODELE=122 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Cascada'
WHERE DCODEMODELE=123 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Corsa'
WHERE DCODEMODELE=124 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Frontera'
WHERE DCODEMODELE=125 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Insignia'
WHERE DCODEMODELE=126 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Insignia kombi'
WHERE DCODEMODELE=127 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Kadett'
WHERE DCODEMODELE=128 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Meriva'
WHERE DCODEMODELE=129 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Mokka'
WHERE DCODEMODELE=130 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Movano'
WHERE DCODEMODELE=131 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Omega'
WHERE DCODEMODELE=132 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Signum'
WHERE DCODEMODELE=133 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Vectra'
WHERE DCODEMODELE=134 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Vectra Caravan'
WHERE DCODEMODELE=135 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Vivaro'
WHERE DCODEMODELE=136 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Opel Vivaro Kombi'
WHERE DCODEMODELE=137 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 145'
WHERE DCODEMODELE=138 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 146'
WHERE DCODEMODELE=139 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 147'
WHERE DCODEMODELE=140 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 155'
WHERE DCODEMODELE=141 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 156'
WHERE DCODEMODELE=142 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 156 Sportwagon'
WHERE DCODEMODELE=143 ;
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 159'
WHERE DCODEMODELE=144 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 159 Sportwagon'
WHERE DCODEMODELE=145 ;
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 164'
WHERE DCODEMODELE=146 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 166'
WHERE DCODEMODELE=147 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo 4C'
WHERE DCODEMODELE=148 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo Brera'
WHERE DCODEMODELE=149 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo GTV'
WHERE DCODEMODELE=150 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo MiTo'
WHERE DCODEMODELE=151 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo Crosswagon'
WHERE DCODEMODELE=152 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo Spider'
WHERE DCODEMODELE=153 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo GT'
WHERE DCODEMODELE=154 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Alfa Romeo Giulietta'
WHERE DCODEMODELE=155 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Favorit'
WHERE DCODEMODELE=156 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Felicia'
WHERE DCODEMODELE=157 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Citigo'
WHERE DCODEMODELE=158 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Fabia'
WHERE DCODEMODELE=159 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Fabia Combi'
WHERE DCODEMODELE=160 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Fabia Sedan'
WHERE DCODEMODELE=161 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Felicia Combi'
WHERE DCODEMODELE=162 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Octavia'
WHERE DCODEMODELE=163 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Octavia Combi'
WHERE DCODEMODELE=164 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Roomster'
WHERE DCODEMODELE=165 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Yeti'
WHERE DCODEMODELE=166 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Rapid'
WHERE DCODEMODELE=167 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Rapid Spaceback'
WHERE DCODEMODELE=168 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Škoda Superb'
WHERE DCODEMODELE=169 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Alero'
WHERE DCODEMODELE=170 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Aveo'
WHERE DCODEMODELE=171 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Camaro'
WHERE DCODEMODELE=172 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Captiva'
WHERE DCODEMODELE=173 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Corvette'
WHERE DCODEMODELE=174 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Cruze'
WHERE DCODEMODELE=175 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Cruze SW'
WHERE DCODEMODELE=176 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Epica'
WHERE DCODEMODELE=177 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Equinox'
WHERE DCODEMODELE=178 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Evanda'
WHERE DCODEMODELE=179 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet HHR'
WHERE DCODEMODELE=180 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Kalos'
WHERE DCODEMODELE=181 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Lacetti'
WHERE DCODEMODELE=182 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Lacetti SW'
WHERE DCODEMODELE=183 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Lumina'
WHERE DCODEMODELE=184 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Malibu'
WHERE DCODEMODELE=185 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Matiz'
WHERE DCODEMODELE=186 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Monte Carlo'
WHERE DCODEMODELE=187 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Nubira'
WHERE DCODEMODELE=188 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Chevrolet Orlando'
WHERE DCODEMODELE=189 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Honda Accord Coupé'
WHERE DCODEMODELE=190 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Honda Accord Tourer'
WHERE DCODEMODELE=191 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Honda City'
WHERE DCODEMODELE=192 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Honda Civic'
WHERE DCODEMODELE=193 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Honda Civic Aerodeck'
WHERE DCODEMODELE=194 ;
 
UPDATE Dmodele
SET DLIBELLEMODELE='Honda Civic Type R'
WHERE DCODEMODELE=195 ;
UPDATE Dmodele
SET DLIBELLEMODELE='Honda CR-V'
WHERE DCODEMODELE=196 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Honda HR-V'
WHERE DCODEMODELE=197 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Honda Insight'
WHERE DCODEMODELE=198 ;
  
UPDATE Dmodele
SET DLIBELLEMODELE='Honda Integra'
WHERE DCODEMODELE=199 ;

UPDATE DMODELE
SET DLIBELLEMODELE='HONDA JAZZ')
WHERE DCODEMODELE=200;